global:
  scrape_interval: 30s
  scrape_timeout: 30s

scrape_configs:
  - job_name: "otherInterestedParty_totalCompletedCount"
    scrape_interval: 60s
    scrape_timeout: 60s
    metrics_path: "/journeyStats/count"
    static_configs:
      - targets: ["cc-prometheus-exporter-itc-ea7e25346311.herokuapp.com"]
        labels:
          group: 'journeyCount'
  - job_name: "journeyAndStepsCompletionTime"
    scrape_interval: 120s
    scrape_timeout: 60s
    metrics_path: "/completedJourneys/steps/basicStats"
    static_configs:
      - targets: ["cc-prometheus-exporter-itc-ea7e25346311.herokuapp.com"]
        labels:
          group: 'journeyTiming'
  - job_name: "ccMetrics"
    scrape_interval: 30s
    scrape_timeout: 60s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cc-prometheus-exporter-itc-ea7e25346311.herokuapp.com"]
        labels:
          group: 'CoreCONNECT'
  