global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:
  - job_name: "otherInterestedParty_totalCompletedCount"
    scrape_interval: 30s
    metrics_path: "/completedJourneys/count/otherInterestedParty"
    static_configs:
      - targets: ["cc-prometheus-exporter-itc-ea7e25346311.herokuapp.com"]
        labels:
          group: 'completedJourneys'
  - job_name: "duplicatePolicyRequest_totalCompletedCount"
    scrape_interval: 30s
    metrics_path: "/completedJourneys/count/duplicatePolicyRequest"
    static_configs:
      - targets: ["cc-prometheus-exporter-itc-ea7e25346311.herokuapp.com"]
        labels:
          group: 'completedJourneys'
  - job_name: "otherInterestedParty_totalCompletion_time"
    scrape_interval: 120s
    metrics_path: "/completedJourneys/steps/basicStats/otherInterestedParty"
    static_configs:
      - targets: ["cc-prometheus-exporter-itc-ea7e25346311.herokuapp.com"]
        labels:
          group: 'journeyTiming'
  