global:
  scrape_interval: 30s
  scrape_timeout: 30s

scrape_configs:
  - job_name: "ccMetrics"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cc-prometheus-exporter-itc-ea7e25346311.herokuapp.com"]
        labels:
          group: 'CoreCONNECT'

  