global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "temporal"
    scrape_interval: 2s
    metrics_path: "/completedJourneys/count/otherInterestedParty"
    static_configs:
      - targets: ["cc-prometheus-exporter-itc-ea7e25346311.herokuapp.com"]
        labels:
          group: 'temporal-2'